version: "3"

services:
  web:
    build: .
    command: daphne -p 8000 -b 0.0.0.0 chat_project.asgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=chat_project.settings
      - REDIS_URL=redis://redis:6379/1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
