services:
  - name: web
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: daphne -p 8000 -b 0.0.0.0 chat_project.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: chat_project.settings
      - key: REDIS_URL
        value: redis://redis:6379/1
    plan: free
    healthCheckPath: /
    disk:
      sizeGB: 10

  - name: redis
    type: redis
    plan: free
